import { useMemo } from 'react';
import { Badge, Button, EmptyState, Status } from '@glint/ui';
import type { DecisionBrief, Destination, Investigation, Signal, WorkspaceState } from '../domain';
import { authenticityLabel } from '../domain';
import { label } from '../lib/formatting';
import { SignalRow } from '../features/inbox/SignalInbox';

export function Sidebar({ destination, workspace, onSelect }: { destination: Destination; workspace: WorkspaceState; onSelect: (value: Destination) => void }) {
  const rows: Array<[Destination, string, string]> = [['inbox', 'Inbox', String(workspace.navigation.unreviewedSignalCount)], ['investigations', 'Investigations', workspace.navigation.investigationNeedsInputCount ? String(workspace.navigation.investigationNeedsInputCount) : ''], ['decisions', 'Decisions', workspace.navigation.draftDecisionBriefCount ? String(workspace.navigation.draftDecisionBriefCount) : ''], ['monitoring', 'Monitoring', workspace.navigation.monitoringHealth === 'degraded' ? 'Degraded' : '']];
  return <nav className="sidebar" aria-label="Primary"><p>WORK</p>{rows.slice(0, 3).map(([id, name, count]) => <button className={destination === id ? 'nav-row active' : 'nav-row'} onClick={() => onSelect(id)} key={id}><span>{name}</span>{count && <Badge tone={id === 'decisions' ? 'warning' : 'neutral'}>{count}</Badge>}</button>)}<p>MANAGE</p>{rows.slice(3).map(([id, name, count]) => <button className={destination === id ? 'nav-row active' : 'nav-row'} onClick={() => onSelect(id)} key={id}><span>{name}</span>{count && <Badge tone="warning">⚠ {count}</Badge>}</button>)}<div className="sidebar-bottom"><small>{workspace.workspaceName}</small><small>{authenticityLabel(workspace.authenticity)}</small></div></nav>;
}

export function ListPane({ destination, workspace, selectedId, filter, setFilter, onSelect }: { destination: Destination; workspace: WorkspaceState; selectedId: string; filter: string; setFilter: (value: string) => void; onSelect: (id: string) => void }) {
  const items = useMemo(() => destination === 'inbox' ? workspace.signals : destination === 'investigations' ? workspace.investigations : destination === 'decisions' ? workspace.briefs : [], [destination, workspace]);
  const titles = { inbox: 'Inbox', investigations: 'Investigations', decisions: 'Decisions', monitoring: 'Monitoring' };
  if (destination === 'monitoring') return <section className="list-pane" aria-label="Monitoring list" tabIndex={-1}><header><h1>Monitoring</h1><p>Source health</p></header><div className="list-empty">Cloud and imported sources are shown in the detail pane.</div></section>;
  const matching = items.filter((item) => ('title' in item ? item.title : 'question' in item ? item.question : '').toLowerCase().includes(filter.toLowerCase()));
  return <section className="list-pane" aria-label={`${titles[destination]} list`} tabIndex={-1}><header><div><h1>{titles[destination]}</h1><span>{matching.length} connected</span></div><input value={filter} onChange={(event) => setFilter(event.target.value)} aria-label={`Search ${titles[destination]}`} placeholder="Filter current list" /></header>{matching.length === 0 ? <EmptyState title="No matching items" body="No connected object matches this filter." action={<Button onClick={() => setFilter('')}>Clear filters</Button>} /> : <div>{destination === 'inbox' && (matching as Signal[]).map((item) => <SignalRow item={item} watchlist={workspace.watchlists.find((watchlist) => watchlist.id === item.watchlistId)} sources={workspace.sources} selected={selectedId === item.id} onClick={() => onSelect(item.id)} key={item.id} />)}{destination === 'investigations' && (matching as Investigation[]).map((item) => <button className={selectedId === item.id ? 'list-row selected' : 'list-row'} onClick={() => onSelect(item.id)} key={item.id}><Status tone={item.status === 'needs_input' ? 'warning' : 'info'}>{label(item.status)}</Status><strong>{item.question}</strong><small>{item.evidence.length} evidence · {item.run ? label(item.run.state) : 'No run'}</small></button>)}{destination === 'decisions' && (matching as DecisionBrief[]).map((item) => <button className={selectedId === item.id ? 'list-row selected' : 'list-row'} onClick={() => onSelect(item.id)} key={item.id}><Status tone={item.status === 'decision_ready' ? 'positive' : 'warning'}>{label(item.status)}</Status><strong>{item.question}</strong><small>v{item.version} · {item.freshness === 'current' ? 'Evidence current' : 'Evidence updated'}</small></button>)}</div>}</section>;
}
