import { useState } from 'react';
import { Button } from '@glint/ui';
import { eligibleResearchSources } from '../../api';
import type { Signal, SourceHealth } from '../../domain';
import { authenticityLabel } from '../../domain';
import { displayTime } from '../../lib/formatting';

export function InvestigationPlanDialog({ signal, sources, disabled, onClose, onRun }: { signal: Signal; sources: SourceHealth[]; disabled: boolean; onClose: () => void; onRun: (question: string, allowCloudModel: boolean) => void }) {
  const [question, setQuestion] = useState(`What decision should we make in response to “${signal.title}”?`);
  const [allowCloudModel, setAllowCloudModel] = useState(false);
  const [egressConfirmed, setEgressConfirmed] = useState(false);
  const eligible = eligibleResearchSources(signal, sources);
  return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label="Investigation plan"><h2>Plan Investigation</h2><p>This run is bounded to the selected Signal-linked, versioned source content. Glint proposals never approve evidence, claims, synthesis, or a Decision Brief.</p><label>Decision Question<textarea value={question} onChange={(event) => setQuestion(event.target.value)} /></label><fieldset className="research-mode"><legend>Research method</legend><label><input type="radio" name="research-method" checked={!allowCloudModel} onChange={() => { setAllowCloudModel(false); setEgressConfirmed(false); }} /> Deterministic research <small>No source content is sent to a model provider.</small></label><label><input type="radio" name="research-method" checked={allowCloudModel} onChange={() => setAllowCloudModel(true)} /> Model-assisted research <small>Uses the workspace-configured DeepSeek model to propose evidence and claims for review.</small></label></fieldset>{allowCloudModel && <section className="egress-confirmation" aria-label="Model egress confirmation"><h3>Confirm model egress for this run</h3><p>Selected source excerpts and the Decision Question may be sent to the configured DeepSeek provider. The full workspace, credentials, approval state, and local file paths are excluded. Imported-upload consent does not grant this model access.</p><label><input type="checkbox" checked={egressConfirmed} onChange={(event) => setEgressConfirmed(event.target.checked)} /> I confirm this run-scoped model egress for the sources, time window, and budget below.</label></section>}<dl><dt>Time window</dt><dd>{displayTime(signal.window.currentStart)} → {displayTime(signal.window.currentEnd)}</dd><dt>Source content</dt><dd>{eligible.map((item) => item.sourceKind === 'imported_dataset' ? `${item.name} · Imported terminal manifest ${item.currentImportManifestId}` : `${item.name} · Cloud ${item.connectorType} collection · ${item.freshness.state} since ${displayTime(item.freshness.lastSuccessAt)}`).join('\n') || 'No Signal-linked source has eligible versioned content'}</dd><dt>Budget</dt><dd>Up to $4.00 / 15 minutes</dd><dt>Authenticity</dt><dd>{authenticityLabel(signal.authenticity)}</dd></dl><div className="modal-actions"><Button onClick={onClose}>Back to Signal</Button><Button className="primary" disabled={disabled || !question.trim() || eligible.length === 0 || (allowCloudModel && !egressConfirmed)} onClick={() => onRun(question, allowCloudModel)}>{allowCloudModel ? 'Run model-assisted research' : 'Run deterministic research'}</Button></div></section></div>;
}
