import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it, vi } from 'vitest';
import { QuantActivityFeed, QuantArtifactCards, QuantKernelCheckCard } from './QuantActivity';
import { QuantDataPage } from './QuantDataPage';
import { QuantGoalComposer } from './QuantGoalComposer';
import { QuantMarketWorkspace } from './QuantMarketWorkspace';
import { QuantPlanRail } from './QuantPlanRail';
import { presentQuantWorkspace } from './quant-presentation';
import { QuantGeneralizationPanel, QuantStrategyReport } from './QuantStrategyReport';
import { quantFixtureSnapshot } from './quant-fixtures';
import { createFixtureQuantApi } from '../../quant-api';

const presentation = presentQuantWorkspace(quantFixtureSnapshot);

describe('Quant Workspace components', () => {
  it('renders all research modes and truthfully gates Auto Research', () => {
    const markup = renderToStaticMarkup(<QuantGoalComposer snapshot={quantFixtureSnapshot} large onSubmit={vi.fn()} />);
    expect(markup).toContain('Ask');
    expect(markup).toContain('Plan');
    expect(markup).toContain('Auto Research');
    expect(markup).toContain('Internet disabled');
    expect(markup).not.toContain('token');
    expect(markup).not.toContain('cost');
  });

  it('renders discrete plan steps, owners, and artifacts without percentage progress', () => {
    const markup = renderToStaticMarkup(<QuantPlanRail steps={quantFixtureSnapshot.plan} currentStepId={quantFixtureSnapshot.run.currentStepId} completedStepCount={presentation.completedStepCount} />);
    expect(markup).toContain('10 of 10 steps');
    expect(markup).toContain('Human gate');
    expect(markup).toContain('Validator');
    expect(markup).not.toMatch(/\d+%/);
  });

  it('renders safe activity copy and hides exact event names from the feed', () => {
    const markup = renderToStaticMarkup(<QuantActivityFeed snapshot={quantFixtureSnapshot} presentation={presentation} onInspect={vi.fn()} />);
    expect(markup).toContain('Candidate rejected by validator');
    expect(markup).toContain('without failing the run');
    expect(markup).not.toContain('candidate.rejected');
  });

  it('labels computed kernel research as synthetic and bounded', () => {
    const markup = renderToStaticMarkup(<QuantKernelCheckCard snapshot={quantFixtureSnapshot} />);
    expect(markup).toContain('Daily-bar kernel verified');
    expect(markup).toContain('1,564 synthetic weekday bars');
    expect(markup).toContain('metrics and trades are generated by this same kernel');
    expect(markup).toContain('No network · no broker · no arbitrary code');
  });

  it('labels market evidence and artifact cards as Synthetic Demo Fixture', () => {
    const market = renderToStaticMarkup(<QuantMarketWorkspace snapshot={quantFixtureSnapshot} onInspect={vi.fn()} />);
    const artifacts = renderToStaticMarkup(<QuantArtifactCards artifacts={presentation.primaryArtifacts} onInspect={vi.fn()} />);
    expect(market).toContain('Synthetic Demo Fixture');
    expect(market).toContain('not live market data');
    expect(artifacts).toContain('Synthetic Demo Fixture');
    expect(artifacts).not.toContain('artifact-research-report');
  });

  it('shows candidate verdicts separately from the completed strategy report', () => {
    const markup = renderToStaticMarkup(<QuantStrategyReport snapshot={quantFixtureSnapshot} candidates={presentation.candidates} selectedCandidateId="candidate-b" onSelectCandidate={vi.fn()} />);
    expect(markup).toContain('Candidate for paper evaluation');
    expect(markup).toContain('Candidate A is rejected');
    expect(markup).toContain('Synthetic Demo Fixture');
    expect(markup).toContain('generalization');
    expect(markup).toContain('Training annualized return');
    expect(markup).not.toContain('Start Paper Trading');
  });

  it('renders a safe unavailable state when a report has no generalization result', () => {
    const markup = renderToStaticMarkup(<QuantGeneralizationPanel />);
    expect(markup).toContain('Generalization unavailable');
    expect(markup).toContain('does not include a chronological train/holdout evaluation');
  });

  it('renders chronological split provenance and train/holdout metrics', () => {
    const candidate = quantFixtureSnapshot.candidates[0]!.metrics;
    const benchmark = quantFixtureSnapshot.benchmark!;
    const markup = renderToStaticMarkup(<QuantGeneralizationPanel generalization={{
      status: 'pass',
      reason: 'The selected candidate remained ahead of the benchmark on holdout data.',
      selectedCandidateId: 'candidate-a',
      split: {
        method: 'chronological',
        ruleVersion: 'chronological-v1',
        trainBarCount: 1200,
        holdoutBarCount: 364,
        cutoffDate: '2024-01-02',
        datasetId: 'dataset-immutable-01',
        datasetDigest: 'sha256:generalization-fixture',
      },
      train: { candidate, benchmark },
      holdout: {
        candidate: { ...candidate, annualizedReturn: 9.4, trades: 5 },
        benchmark: { ...benchmark, annualizedReturn: 7.2, trades: 1 },
      },
    }} />);
    expect(markup).toContain('Chronological generalization');
    expect(markup).toContain('The selected candidate remained ahead');
    expect(markup).toContain('chronological-v1');
    expect(markup).toContain('1200');
    expect(markup).toContain('364');
    expect(markup).toContain('2024-01-02');
    expect(markup).toContain('candidate-a');
    expect(markup).toContain('dataset-immutable-01');
    expect(markup).toContain('sha256:generalization-fixture');
    expect(markup).toContain('Training metrics');
    expect(markup).toContain('Holdout metrics');
    expect(markup).toContain('9.4%');
  });

  it('uses imported provenance and symbol copy for imported evidence', () => {
    const importedSnapshot = {
      ...quantFixtureSnapshot,
      authenticity: 'imported_fixture' as const,
      scope: { ...quantFixtureSnapshot.scope, symbol: 'ACME' },
      dataset: { ...quantFixtureSnapshot.dataset, symbol: 'ACME', authenticity: 'imported_fixture' as const },
    };
    const market = renderToStaticMarkup(<QuantMarketWorkspace snapshot={importedSnapshot} onInspect={vi.fn()} />);
    const report = renderToStaticMarkup(<QuantStrategyReport snapshot={importedSnapshot} candidates={presentation.candidates} selectedCandidateId="candidate-b" onSelectCandidate={vi.fn()} />);
    expect(market).toContain('ACME daily market chart');
    expect(market).toContain('workspace-imported dataset');
    expect(report).toContain('Imported Demo Fixture');
    expect(report).not.toContain('Synthetic Demo Fixture');
  });

  it('renders an immutable CSV import boundary and dataset eligibility', () => {
    const markup = renderToStaticMarkup(<QuantDataPage api={createFixtureQuantApi()} snapshot={quantFixtureSnapshot} selectedDataset={quantFixtureSnapshot.dataset} onSelect={vi.fn()} onInspect={vi.fn()} />);
    expect(markup).toContain('OHLCV CSV file');
    expect(markup).toContain('Import immutable dataset');
    expect(markup).toContain('Ready for Auto Research');
    expect(markup).toContain(quantFixtureSnapshot.dataset.digest.slice(0, 19));
  });
});
