import { Badge, Button, Status } from '@glint/ui';
import type { QuantArtifact, QuantWorkspaceSnapshot } from '../../quant-domain';
import { quantAuthenticityLabel } from '../../quant-domain';
import type { QuantActionPresentation, QuantActivityPresentation, QuantWorkspacePresentation } from './quant-presentation';

function displayTime(value: string): string {
  return new Intl.DateTimeFormat('en', { hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value));
}

export function QuantActionCenter({ presentation, onAction }: { presentation: QuantWorkspacePresentation; onAction: (action: QuantActionPresentation) => void }) {
  if (presentation.actions.length === 0) return null;
  return <section className={`quant-action-center tone-${presentation.statusTone}`} aria-labelledby="quant-action-title">
    <div><p className="quant-eyebrow">Action Center</p><h3 id="quant-action-title">{presentation.currentActionTitle}</h3><p>{presentation.currentActionPurpose}</p><small>Lifecycle controls come from the API snapshot; view actions open persisted artifacts.</small></div>
    <div className="quant-action-buttons">{presentation.actions.map((action) => <Button className={action.tone === 'primary' ? 'primary' : ''} key={action.kind} onClick={() => onAction(action)}>{action.label}</Button>)}</div>
  </section>;
}

export function QuantActivityFeed({ snapshot, presentation, onInspect }: {
  snapshot: QuantWorkspaceSnapshot;
  presentation: QuantWorkspacePresentation;
  onInspect: (event: QuantActivityPresentation) => void;
}) {
  return <section className="quant-activity" aria-label="Run activity">
    <article className={`quant-current-action tone-${presentation.statusTone}`}>
      <header><div><p className="quant-eyebrow">Current state</p><h3>{presentation.currentActionTitle}</h3></div><Status tone={presentation.statusTone}>{presentation.statusLabel}</Status></header>
      <p>{presentation.currentActionPurpose}</p>
      <dl><div><dt>Iteration</dt><dd>{snapshot.run.agentIteration} / {snapshot.run.maxAgentIterations}</dd></div><div><dt>Experiments</dt><dd>{snapshot.run.usedExperiments} / {snapshot.limits.maxExperiments}</dd></div><div><dt>Repairs</dt><dd>{snapshot.run.usedRepairAttempts} / {snapshot.limits.maxRepairAttempts}</dd></div></dl>
    </article>
    <div className="quant-panel-heading"><div><p className="quant-eyebrow">Activity</p><h3>Durable run events</h3></div><span>{presentation.activity.length} shown</span></div>
    <ol className="quant-activity-list">
      {presentation.activity.map((event) => <li key={event.id} className={`quant-activity-${event.kind}`}><span className="quant-activity-dot" aria-hidden="true" /><div><div className="quant-event-title"><strong>{event.title}</strong><time dateTime={event.timestamp}>{displayTime(event.timestamp)}</time></div>{event.action && <dl><div><dt>Action</dt><dd><code>{event.action}</code></dd></div>{event.expectedResult && <div><dt>Expected result</dt><dd>{event.expectedResult}</dd></div>}</dl>}<p>{event.summary}</p><footer><Badge tone="neutral">{event.actorLabel}</Badge>{event.artifactId && <span>Artifact retained</span>}<button onClick={() => onInspect(event)} aria-label={`Inspect ${event.title}`}>Inspect</button></footer></div></li>)}
    </ol>
  </section>;
}

export function QuantKernelCheckCard({ snapshot }: { snapshot: QuantWorkspaceSnapshot }) {
  const check = snapshot.kernelCheck;
  const verified = check.status === 'verified' && check.benchmark !== null;
  const splitAware = check.limitations.some((item) => item.includes('training partition'));
  const datasetLabel = snapshot.authenticity === 'synthetic_fixture' ? 'synthetic weekday' : 'workspace-imported';
  return <article className="quant-kernel-check" aria-label="Daily-bar kernel verification">
    <header><div><p className="quant-eyebrow">Executable evidence</p><h3>Daily-bar kernel {verified ? 'verified' : 'ready'}</h3></div><Status tone={verified ? 'positive' : 'neutral'}>{check.status}</Status></header>
    <p>{verified ? splitAware ? `Pure local research from the ${check.barCount.toLocaleString()}-bar ${datasetLabel} dataset. Candidate selection metrics use only the training partition; sealed holdout evidence is retained in Generalization.` : `Pure local research run over ${check.barCount.toLocaleString()} ${datasetLabel} bars. Candidate metrics and trades are generated by this same kernel.` : `The digest-pinned ${check.barCount.toLocaleString()}-bar ${datasetLabel} dataset and fixed strategy specs are ready. Results remain hidden until the API advances the run.`}</p>
    <dl><div><dt>{verified ? splitAware ? 'Training benchmark annualized' : 'Benchmark annualized' : 'Results'}</dt><dd>{verified && check.benchmark ? `${check.benchmark.annualizedReturnPct >= 0 ? '+' : ''}${check.benchmark.annualizedReturnPct.toFixed(2)}%` : 'Pending Agent run'}</dd></div><div><dt>Strategies</dt><dd>{verified ? `${check.strategies.length} computed specs` : '3 fixed specs'}</dd></div><div><dt>Execution</dt><dd>Close signal → next open</dd></div><div><dt>Costs</dt><dd>{check.feeRateBps} bps fee · {check.slippageRateBps} bps slippage</dd></div></dl>
    <footer><span>No network · no broker · no arbitrary code</span><code title={check.datasetDigest}>{check.datasetDigest.slice(0, 19)}…</code></footer>
  </article>;
}

export function QuantArtifactCards({ artifacts, onInspect }: { artifacts: QuantArtifact[]; onInspect: (artifact: QuantArtifact) => void }) {
  return <section className="quant-artifacts" aria-labelledby="quant-artifact-title">
    <div className="quant-panel-heading"><div><p className="quant-eyebrow">Artifacts</p><h3 id="quant-artifact-title">Governed output</h3></div><span>{artifacts.length}</span></div>
    <div className="quant-artifact-grid">{artifacts.map((artifact) => <article key={artifact.id} className={`quant-artifact-card type-${artifact.type}`}>
      <header><div><p className="quant-eyebrow">{artifact.type.replaceAll('_', ' ')}</p><h4>{artifact.title}</h4></div><Status tone={artifact.status === 'reviewed' ? 'positive' : artifact.status === 'rejected' ? 'danger' : 'neutral'}>{artifact.status}</Status></header>
      <p>{artifact.summary}</p><div><Badge tone="neutral">{artifact.origin}</Badge><Badge tone="warning">{quantAuthenticityLabel(artifact.authenticity)}</Badge><span>{artifact.relatedLabel}</span></div><Button onClick={() => onInspect(artifact)}>Inspect artifact</Button>
    </article>)}</div>
  </section>;
}
