import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it, vi } from 'vitest';
import { QuantActivityFeed, QuantArtifactCards, QuantKernelCheckCard } from './QuantActivity';
import { QuantDataPage } from './QuantDataPage';
import { QuantGoalComposer, quantDatasetReadyForAutoResearch } from './QuantGoalComposer';
import { QuantMarketWorkspace } from './QuantMarketWorkspace';
import { QuantPlanRail } from './QuantPlanRail';
import { presentQuantWorkspace } from './quant-presentation';
import { QuantGeneralizationPanel, QuantStrategyReport } from './QuantStrategyReport';
import { quantFixtureSnapshot } from './quant-fixtures';
import { createFixtureQuantApi } from '../../quant-api';

const presentation = presentQuantWorkspace(quantFixtureSnapshot);
const datasetQuality = {
  schemaVersion: 'quant-data-quality-v1',
  policyVersion: 'ohlcv-quality-v1',
  status: 'warning' as const,
  verificationStatus: 'checked' as const,
  reportDigest: 'sha256:data-quality-report',
  datasetDigest: 'sha256:data-quality-dataset',
  barCount: 1564,
  calendarGapCount: 4,
  largestCalendarGapDays: 3,
  zeroVolumeBarCount: 2,
  priceJumpCount: 1,
  issues: [{ code: 'calendar_gap', severity: 'warning', message: 'Calendar gaps need an exchange calendar to interpret.', count: 4 }],
  notes: ['Input checks do not establish market-data authenticity.'],
};

describe('Quant Workspace components', () => {
  it('renders all research modes and truthfully gates Auto Research', () => {
    const markup = renderToStaticMarkup(<QuantGoalComposer snapshot={quantFixtureSnapshot} large onSubmit={vi.fn()} />);
    expect(markup).toContain('Ask');
    expect(markup).toContain('Plan');
    expect(markup).toContain('Auto Research');
    expect(markup).toContain('Internet disabled');
    expect(markup).not.toContain('token');
    expect(markup).not.toContain('cost');
  });

  it('does not enable Auto Research for a quality-blocked dataset', () => {
    expect(quantDatasetReadyForAutoResearch({
      ...quantFixtureSnapshot.dataset,
      quality: { ...datasetQuality, status: 'blocked', verificationStatus: 'rejected' },
    })).toBe(false);
    expect(quantDatasetReadyForAutoResearch(quantFixtureSnapshot.dataset)).toBe(true);
  });

  it('renders discrete plan steps, owners, and artifacts without percentage progress', () => {
    const markup = renderToStaticMarkup(<QuantPlanRail steps={quantFixtureSnapshot.plan} currentStepId={quantFixtureSnapshot.run.currentStepId} completedStepCount={presentation.completedStepCount} />);
    expect(markup).toContain('10 of 10 steps');
    expect(markup).toContain('Human gate');
    expect(markup).toContain('Validator');
    expect(markup).not.toMatch(/\d+%/);
  });

  it('renders safe activity copy and hides exact event names from the feed', () => {
    const markup = renderToStaticMarkup(<QuantActivityFeed snapshot={quantFixtureSnapshot} presentation={presentation} onInspect={vi.fn()} />);
    expect(markup).toContain('Candidate rejected by validator');
    expect(markup).toContain('without failing the run');
    expect(markup).not.toContain('candidate.rejected');
  });

  it('labels computed kernel research as synthetic and bounded', () => {
    const markup = renderToStaticMarkup(<QuantKernelCheckCard snapshot={quantFixtureSnapshot} />);
    expect(markup).toContain('Daily-bar kernel verified');
    expect(markup).toContain('1,564 synthetic weekday bars');
    expect(markup).toContain('metrics and trades are generated by this same kernel');
    expect(markup).toContain('No network · no broker · no arbitrary code');
  });

  it('labels market evidence and artifact cards as Synthetic Demo Fixture', () => {
    const market = renderToStaticMarkup(<QuantMarketWorkspace snapshot={quantFixtureSnapshot} onInspect={vi.fn()} />);
    const artifacts = renderToStaticMarkup(<QuantArtifactCards artifacts={presentation.primaryArtifacts} onInspect={vi.fn()} />);
    expect(market).toContain('Synthetic Demo Fixture');
    expect(market).toContain('not live market data');
    expect(artifacts).toContain('Synthetic Demo Fixture');
    expect(artifacts).not.toContain('artifact-research-report');
  });

  it('shows candidate verdicts separately from the completed strategy report', () => {
    const markup = renderToStaticMarkup(<QuantStrategyReport snapshot={quantFixtureSnapshot} candidates={presentation.candidates} selectedCandidateId="candidate-b" onSelectCandidate={vi.fn()} />);
    expect(markup).toContain('Candidate for paper evaluation');
    expect(markup).toContain('Candidate A is rejected');
    expect(markup).toContain('Synthetic Demo Fixture');
    expect(markup).toContain('generalization');
    expect(markup).toContain('Training annualized return');
    expect(markup).not.toContain('Start Paper Trading');
  });

  it('renders a safe unavailable state when a report has no generalization result', () => {
    const markup = renderToStaticMarkup(<QuantGeneralizationPanel />);
    expect(markup).toContain('Generalization unavailable');
    expect(markup).toContain('does not include a chronological train/holdout evaluation');
  });

  it('renders chronological split provenance and train/holdout metrics', () => {
    const candidate = quantFixtureSnapshot.candidates[0]!.metrics;
    const benchmark = quantFixtureSnapshot.benchmark!;
    const markup = renderToStaticMarkup(<QuantGeneralizationPanel generalization={{
      status: 'pass',
      reason: 'The selected candidate remained ahead of the benchmark on holdout data.',
      selectedCandidateId: 'candidate-a',
      split: {
        method: 'chronological',
        ruleVersion: 'chronological-v1',
        trainBarCount: 1200,
        holdoutBarCount: 364,
        cutoffDate: '2024-01-02',
        datasetId: 'dataset-immutable-01',
        datasetDigest: 'sha256:generalization-fixture',
      },
      train: { candidate, benchmark },
      holdout: {
        candidate: { ...candidate, annualizedReturn: 9.4, trades: 5 },
        benchmark: { ...benchmark, annualizedReturn: 7.2, trades: 1 },
      },
    }} walkForward={{
      method: 'expanding',
      ruleVersion: 'expanding-3fold-20pct-v1',
      evaluationPartition: 'train',
      foldCount: 3,
      windowBarCount: 48,
      status: 'completed',
      reason: 'Fixed candidate evaluated in three expanding training-only windows.',
      folds: [1, 2, 3].map((foldIndex) => ({
        foldIndex,
        historyStart: '2023-01-01',
        historyEnd: '2023-04-06',
        evaluationStart: `2023-0${foldIndex + 3}-07`,
        evaluationEnd: `2023-0${foldIndex + 4}-24`,
        candidate,
        benchmark,
        status: 'pass' as const,
      })),
      aggregate: {
        evaluatedFolds: 3,
        candidatePositiveReturnFolds: 3,
        candidateLowerDrawdownFolds: 2,
        candidateMedianReturn: 8,
        benchmarkMedianReturn: 7,
        candidateMedianDrawdown: -4,
        benchmarkMedianDrawdown: -6,
        candidateMedianSharpe: 1.2,
        benchmarkMedianSharpe: 1,
      },
    }} datasetQuality={datasetQuality} />);
    expect(markup).toContain('Chronological generalization');
    expect(markup).toContain('The selected candidate remained ahead');
    expect(markup).toContain('chronological-v1');
    expect(markup).toContain('1200');
    expect(markup).toContain('364');
    expect(markup).toContain('2024-01-02');
    expect(markup).toContain('candidate-a');
    expect(markup).toContain('dataset-immutable-01');
    expect(markup).toContain('sha256:generalization-fixture');
    expect(markup).toContain('Training metrics');
    expect(markup).toContain('Holdout metrics');
    expect(markup).toContain('9.4%');
    expect(markup).toContain('Training walk-forward robustness');
    expect(markup).toContain('expanding-3fold-20pct-v1');
    expect(markup).toContain('visible training evidence, not the sealed final holdout');
    expect(markup).toContain('3 / 3');
    expect(markup).toContain('Dataset quality (pinned version)');
    expect(markup).toContain('1,564');
    expect(markup).toContain('Quality checks describe the pinned input, not market-data authenticity or strategy performance.');
  });

  it('uses imported provenance and symbol copy for imported evidence', () => {
    const importedSnapshot = {
      ...quantFixtureSnapshot,
      authenticity: 'imported_fixture' as const,
      scope: { ...quantFixtureSnapshot.scope, symbol: 'ACME' },
      dataset: { ...quantFixtureSnapshot.dataset, symbol: 'ACME', authenticity: 'imported_fixture' as const },
    };
    const market = renderToStaticMarkup(<QuantMarketWorkspace snapshot={importedSnapshot} onInspect={vi.fn()} />);
    const report = renderToStaticMarkup(<QuantStrategyReport snapshot={importedSnapshot} candidates={presentation.candidates} selectedCandidateId="candidate-b" onSelectCandidate={vi.fn()} />);
    expect(market).toContain('ACME daily market chart');
    expect(market).toContain('workspace-imported dataset');
    expect(report).toContain('Imported Dataset');
    expect(report).not.toContain('Synthetic Demo Fixture');
  });

  it('falls back to the report-selected candidate for dynamic provider IDs', () => {
    const snapshot = {
      ...quantFixtureSnapshot,
      report: {
        ...quantFixtureSnapshot.report!,
        generalization: {
          status: 'pass' as const,
          reason: 'Selected after comparison.',
          selectedCandidateId: 'candidate-c',
          split: {
            method: 'chronological' as const,
            ruleVersion: 'chronological-80-20-v1',
            trainBarCount: 1200,
            holdoutBarCount: 300,
            cutoffDate: '2024-01-01',
            datasetId: 'dataset-1',
            datasetDigest: 'sha256:selected-candidate',
          },
        },
      },
    };
    const markup = renderToStaticMarkup(<QuantStrategyReport snapshot={snapshot} candidates={presentation.candidates} selectedCandidateId="provider-specific-id" onSelectCandidate={vi.fn()} />);
    expect(markup).toContain('value="candidate-c" selected=""');
    expect(markup).toContain('16.3%');
  });

  it('renders an immutable CSV import boundary and dataset eligibility', () => {
    const markup = renderToStaticMarkup(<QuantDataPage api={createFixtureQuantApi()} snapshot={quantFixtureSnapshot} selectedDataset={quantFixtureSnapshot.dataset} onSelect={vi.fn()} onInspect={vi.fn()} />);
    expect(markup).toContain('OHLCV CSV file');
    expect(markup).toContain('Import immutable dataset');
    expect(markup).toContain('Binance Spot daily OHLCV');
    expect(markup).toContain('Binance Spot symbol');
    expect(markup).toContain('Default BTCUSDT · 365 daily bars');
    expect(markup).toContain('Dataset source provider');
    expect(markup).toContain('Dataset source reference');
    expect(markup).toContain('Dataset market calendar');
    expect(markup).toContain('Dataset market timezone');
    expect(markup).toContain('Dataset price adjustment');
    expect(markup).toContain('Unavailable for this legacy or synthetic snapshot.');
    expect(markup).toContain('Ready for Auto Research');
    expect(markup).toContain(quantFixtureSnapshot.dataset.digest.slice(0, 19));
  });

  it('renders optional imported data quality without requiring it in legacy snapshots', () => {
    const snapshot = { ...quantFixtureSnapshot, dataset: { ...quantFixtureSnapshot.dataset, quality: datasetQuality } };
    const markup = renderToStaticMarkup(<QuantDataPage api={createFixtureQuantApi()} snapshot={snapshot} selectedDataset={snapshot.dataset} onSelect={vi.fn()} onInspect={vi.fn()} />);
    expect(markup).toContain('warning · 1,564 checked bars · 2 zero-volume · 4 calendar gaps');
  });

  it('renders retained provider-fetch provenance without changing CSV compatibility', () => {
    const snapshot = {
      ...quantFixtureSnapshot,
      dataset: {
        ...quantFixtureSnapshot.dataset,
        source: {
          kind: 'provider_fetch' as const,
          sourceName: 'Binance Spot public market data',
          sourceReference: 'binance-vision:/api/v3/klines',
          submittedCsvDigest: 'sha256:normalized-csv',
          marketCalendar: '24x7' as const,
          timeZone: 'UTC',
          priceAdjustment: 'unadjusted' as const,
          providerId: 'binance_spot',
          providerResponseDigest: 'sha256:provider-response',
          retrievedAt: '2026-07-18T00:00:00Z',
          requestedLimit: 365,
          returnedBarCount: 364,
          droppedIncompleteCount: 1,
          normalizationNote: 'Dropped the incomplete current daily candle.',
          attestationStatus: 'provider_retrieved',
        },
      },
    };
    const markup = renderToStaticMarkup(<QuantDataPage api={createFixtureQuantApi()} snapshot={snapshot} selectedDataset={snapshot.dataset} onSelect={vi.fn()} onInspect={vi.fn()} />);
    expect(markup).toContain('binance_spot');
    expect(markup).toContain('364 bars from 365 requested · 1 incomplete dropped · provider_retrieved');
    expect(markup).toContain('Dropped the incomplete current daily candle.');
  });
});
